# Project: c2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = c3.o
LINKOBJ  = c3.o
LIBS     = -L"D:/A/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -m32
INCS     = -I"D:/A/programs/Dev-Cpp/MinGW64/include" -I"D:/A/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/A/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/A/programs/Dev-Cpp/MinGW64/include" -I"D:/A/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/A/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/A/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = c2.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

c3.o: c3.cpp
	$(CPP) -c c3.cpp -o c3.o $(CXXFLAGS)
